// Code generated by protoc-gen-go. DO NOT EDIT.
// source: space.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PathInfoRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PathInfoRequest) Reset()         { *m = PathInfoRequest{} }
func (m *PathInfoRequest) String() string { return proto.CompactTextString(m) }
func (*PathInfoRequest) ProtoMessage()    {}
func (*PathInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8a3f24abfdc04ca, []int{0}
}

func (m *PathInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathInfoRequest.Unmarshal(m, b)
}
func (m *PathInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathInfoRequest.Marshal(b, m, deterministic)
}
func (m *PathInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathInfoRequest.Merge(m, src)
}
func (m *PathInfoRequest) XXX_Size() int {
	return xxx_messageInfo_PathInfoRequest.Size(m)
}
func (m *PathInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PathInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PathInfoRequest proto.InternalMessageInfo

func (m *PathInfoRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type PathInfoResponse struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IpfsHash             string   `protobuf:"bytes,2,opt,name=ipfsHash,proto3" json:"ipfsHash,omitempty"`
	IsDir                bool     `protobuf:"varint,3,opt,name=isDir,proto3" json:"isDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PathInfoResponse) Reset()         { *m = PathInfoResponse{} }
func (m *PathInfoResponse) String() string { return proto.CompactTextString(m) }
func (*PathInfoResponse) ProtoMessage()    {}
func (*PathInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8a3f24abfdc04ca, []int{1}
}

func (m *PathInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathInfoResponse.Unmarshal(m, b)
}
func (m *PathInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathInfoResponse.Marshal(b, m, deterministic)
}
func (m *PathInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathInfoResponse.Merge(m, src)
}
func (m *PathInfoResponse) XXX_Size() int {
	return xxx_messageInfo_PathInfoResponse.Size(m)
}
func (m *PathInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PathInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PathInfoResponse proto.InternalMessageInfo

func (m *PathInfoResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *PathInfoResponse) GetIpfsHash() string {
	if m != nil {
		return m.IpfsHash
	}
	return ""
}

func (m *PathInfoResponse) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

type GenerateKeyPairRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateKeyPairRequest) Reset()         { *m = GenerateKeyPairRequest{} }
func (m *GenerateKeyPairRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateKeyPairRequest) ProtoMessage()    {}
func (*GenerateKeyPairRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8a3f24abfdc04ca, []int{2}
}

func (m *GenerateKeyPairRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateKeyPairRequest.Unmarshal(m, b)
}
func (m *GenerateKeyPairRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateKeyPairRequest.Marshal(b, m, deterministic)
}
func (m *GenerateKeyPairRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateKeyPairRequest.Merge(m, src)
}
func (m *GenerateKeyPairRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateKeyPairRequest.Size(m)
}
func (m *GenerateKeyPairRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateKeyPairRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateKeyPairRequest proto.InternalMessageInfo

type GenerateKeyPairResponse struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	PrivateKey           string   `protobuf:"bytes,2,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateKeyPairResponse) Reset()         { *m = GenerateKeyPairResponse{} }
func (m *GenerateKeyPairResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateKeyPairResponse) ProtoMessage()    {}
func (*GenerateKeyPairResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8a3f24abfdc04ca, []int{3}
}

func (m *GenerateKeyPairResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateKeyPairResponse.Unmarshal(m, b)
}
func (m *GenerateKeyPairResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateKeyPairResponse.Marshal(b, m, deterministic)
}
func (m *GenerateKeyPairResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateKeyPairResponse.Merge(m, src)
}
func (m *GenerateKeyPairResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateKeyPairResponse.Size(m)
}
func (m *GenerateKeyPairResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateKeyPairResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateKeyPairResponse proto.InternalMessageInfo

func (m *GenerateKeyPairResponse) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *GenerateKeyPairResponse) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func init() {
	proto.RegisterType((*PathInfoRequest)(nil), "space.PathInfoRequest")
	proto.RegisterType((*PathInfoResponse)(nil), "space.PathInfoResponse")
	proto.RegisterType((*GenerateKeyPairRequest)(nil), "space.GenerateKeyPairRequest")
	proto.RegisterType((*GenerateKeyPairResponse)(nil), "space.GenerateKeyPairResponse")
}

func init() {
	proto.RegisterFile("space.proto", fileDescriptor_b8a3f24abfdc04ca)
}

var fileDescriptor_b8a3f24abfdc04ca = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x6a, 0x25, 0x9d, 0x1e, 0x2a, 0x83, 0xb4, 0x4b, 0xd0, 0x52, 0x16, 0x84, 0x9e, 0x7a,
	0xd0, 0x3f, 0xa0, 0x20, 0x56, 0xe9, 0xa5, 0xc4, 0x43, 0x05, 0x4f, 0xdb, 0x30, 0x25, 0x0b, 0x92,
	0x1d, 0x77, 0xb7, 0x42, 0x7f, 0xbc, 0x20, 0x66, 0xd7, 0x56, 0xd2, 0x7a, 0xea, 0x2d, 0xef, 0x23,
	0x33, 0xef, 0x0d, 0x0b, 0x1d, 0xc7, 0xaa, 0xa0, 0x31, 0x5b, 0xe3, 0x0d, 0xb6, 0x6a, 0x20, 0xaf,
	0xa1, 0x3b, 0x53, 0xbe, 0x7c, 0xae, 0x96, 0x26, 0xa7, 0x8f, 0x15, 0x39, 0x8f, 0x08, 0xa7, 0xac,
	0x7c, 0x29, 0x92, 0x61, 0x32, 0x6a, 0xe7, 0xf5, 0xb7, 0x7c, 0x85, 0xf3, 0xad, 0xcd, 0xb1, 0xa9,
	0x1c, 0xed, 0xf3, 0x61, 0x06, 0xa9, 0xe6, 0xa5, 0x7b, 0x52, 0xae, 0x14, 0xc7, 0x35, 0xbf, 0xc1,
	0x78, 0x01, 0x2d, 0xed, 0x1e, 0xb4, 0x15, 0x27, 0xc3, 0x64, 0x94, 0xe6, 0x01, 0x48, 0x01, 0xbd,
	0x09, 0x55, 0x64, 0x95, 0xa7, 0x29, 0xad, 0x67, 0x4a, 0xdb, 0x98, 0x43, 0xce, 0xa1, 0xbf, 0xa3,
	0xc4, 0xd5, 0x97, 0xd0, 0xe6, 0xd5, 0xe2, 0x5d, 0x17, 0x53, 0x5a, 0xc7, 0xfd, 0x5b, 0x02, 0x07,
	0x00, 0x6c, 0xf5, 0x67, 0xf8, 0x2f, 0xc6, 0xf8, 0xc3, 0xdc, 0x7c, 0x25, 0x90, 0xbe, 0xfc, 0xb4,
	0xbf, 0x67, 0x8d, 0x77, 0xd0, 0x99, 0x90, 0xff, 0x2d, 0x87, 0xbd, 0x71, 0x38, 0x52, 0xe3, 0x28,
	0x59, 0x7f, 0x87, 0x0f, 0x51, 0xe4, 0x11, 0xe6, 0xd0, 0x6d, 0xe4, 0xc4, 0xab, 0xe8, 0xde, 0xdf,
	0x2c, 0x1b, 0xfc, 0x27, 0x6f, 0x66, 0xbe, 0x81, 0x68, 0x88, 0x73, 0xed, 0xcb, 0x47, 0x63, 0x0b,
	0x3a, 0x78, 0xf8, 0xe2, 0xac, 0x7e, 0x01, 0xb7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x88,
	0xa6, 0x21, 0x10, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SpaceApiClient is the client API for SpaceApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpaceApiClient interface {
	GetPathInfo(ctx context.Context, in *PathInfoRequest, opts ...grpc.CallOption) (*PathInfoResponse, error)
	GenerateKeyPair(ctx context.Context, in *GenerateKeyPairRequest, opts ...grpc.CallOption) (*GenerateKeyPairResponse, error)
	GenerateKeyPairWithForce(ctx context.Context, in *GenerateKeyPairRequest, opts ...grpc.CallOption) (*GenerateKeyPairResponse, error)
}

type spaceApiClient struct {
	cc grpc.ClientConnInterface
}

func NewSpaceApiClient(cc grpc.ClientConnInterface) SpaceApiClient {
	return &spaceApiClient{cc}
}

func (c *spaceApiClient) GetPathInfo(ctx context.Context, in *PathInfoRequest, opts ...grpc.CallOption) (*PathInfoResponse, error) {
	out := new(PathInfoResponse)
	err := c.cc.Invoke(ctx, "/space.SpaceApi/GetPathInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceApiClient) GenerateKeyPair(ctx context.Context, in *GenerateKeyPairRequest, opts ...grpc.CallOption) (*GenerateKeyPairResponse, error) {
	out := new(GenerateKeyPairResponse)
	err := c.cc.Invoke(ctx, "/space.SpaceApi/GenerateKeyPair", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceApiClient) GenerateKeyPairWithForce(ctx context.Context, in *GenerateKeyPairRequest, opts ...grpc.CallOption) (*GenerateKeyPairResponse, error) {
	out := new(GenerateKeyPairResponse)
	err := c.cc.Invoke(ctx, "/space.SpaceApi/GenerateKeyPairWithForce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpaceApiServer is the server API for SpaceApi service.
type SpaceApiServer interface {
	GetPathInfo(context.Context, *PathInfoRequest) (*PathInfoResponse, error)
	GenerateKeyPair(context.Context, *GenerateKeyPairRequest) (*GenerateKeyPairResponse, error)
	GenerateKeyPairWithForce(context.Context, *GenerateKeyPairRequest) (*GenerateKeyPairResponse, error)
}

// UnimplementedSpaceApiServer can be embedded to have forward compatible implementations.
type UnimplementedSpaceApiServer struct {
}

func (*UnimplementedSpaceApiServer) GetPathInfo(ctx context.Context, req *PathInfoRequest) (*PathInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPathInfo not implemented")
}
func (*UnimplementedSpaceApiServer) GenerateKeyPair(ctx context.Context, req *GenerateKeyPairRequest) (*GenerateKeyPairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateKeyPair not implemented")
}
func (*UnimplementedSpaceApiServer) GenerateKeyPairWithForce(ctx context.Context, req *GenerateKeyPairRequest) (*GenerateKeyPairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateKeyPairWithForce not implemented")
}

func RegisterSpaceApiServer(s *grpc.Server, srv SpaceApiServer) {
	s.RegisterService(&_SpaceApi_serviceDesc, srv)
}

func _SpaceApi_GetPathInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceApiServer).GetPathInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/space.SpaceApi/GetPathInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceApiServer).GetPathInfo(ctx, req.(*PathInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceApi_GenerateKeyPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKeyPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceApiServer).GenerateKeyPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/space.SpaceApi/GenerateKeyPair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceApiServer).GenerateKeyPair(ctx, req.(*GenerateKeyPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceApi_GenerateKeyPairWithForce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKeyPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceApiServer).GenerateKeyPairWithForce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/space.SpaceApi/GenerateKeyPairWithForce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceApiServer).GenerateKeyPairWithForce(ctx, req.(*GenerateKeyPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpaceApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "space.SpaceApi",
	HandlerType: (*SpaceApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPathInfo",
			Handler:    _SpaceApi_GetPathInfo_Handler,
		},
		{
			MethodName: "GenerateKeyPair",
			Handler:    _SpaceApi_GenerateKeyPair_Handler,
		},
		{
			MethodName: "GenerateKeyPairWithForce",
			Handler:    _SpaceApi_GenerateKeyPairWithForce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "space.proto",
}
