# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
project_name: space
builds:
  - id: space
    # env:
    #   - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.mongousr={{ .Env.MONGO_USR }}
      - -X main.mongopw={{ .Env.MONGO_PW }}
      - -X main.mongohost={{ .Env.MONGO_HOST }}
      - -X main.mongorepset={{ .Env.MONGO_REPLICA_SET }}
      - -X main.spaceapi={{ .Env.SERVICES_API_URL }}
      - -X main.vaultapi={{ .Env.VAULT_API_URL }}
      - -X main.vaultsaltsecret={{ .Env.VAULT_SALT_SECRET }}
      - -X main.spacehubauth={{ .Env.SERVICES_HUB_AUTH_URL }}
      - -X main.textilehub={{ .Env.TXL_HUB_TARGET }}
      - -X main.textilehubma={{ .Env.TXL_HUB_MA }}
      - -X main.textilethreads={{ .Env.TXL_THREADS_TARGET }}
      - -X main.textilehubgatewayurl={{ .Env.TXL_HUB_GATEWAY_URL }}
      - -X main.textileuserkey={{ .Env.TXL_USER_KEY }}
      - -X main.textileusersecret={{ .Env.TXL_USER_SECRET }}
      - -X main.spacestoragesiteurl={{ .Env.SPACE_STORAGE_SITE_URL }}
    main: ./cmd/space-daemon/main.go
    binary: space
    goos:
      - linux

  - id: space-darwin
    # env:
    #   - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.mongousr={{ .Env.MONGO_USR }}
      - -X main.mongopw={{ .Env.MONGO_PW }}
      - -X main.mongohost={{ .Env.MONGO_HOST }}
      - -X main.mongorepset={{ .Env.MONGO_REPLICA_SET }}
      - -X main.spaceapi={{ .Env.SERVICES_API_URL }}
      - -X main.vaultapi={{ .Env.VAULT_API_URL }}
      - -X main.vaultsaltsecret={{ .Env.VAULT_SALT_SECRET }}
      - -X main.spacehubauth={{ .Env.SERVICES_HUB_AUTH_URL }}
      - -X main.textilehub={{ .Env.TXL_HUB_TARGET }}
      - -X main.textilehubma={{ .Env.TXL_HUB_MA }}
      - -X main.textilethreads={{ .Env.TXL_THREADS_TARGET }}
      - -X main.textilehubgatewayurl={{ .Env.TXL_HUB_GATEWAY_URL }}
      - -X main.textileuserkey={{ .Env.TXL_USER_KEY }}
      - -X main.textileusersecret={{ .Env.TXL_USER_SECRET }}
      - -X main.spacestoragesiteurl={{ .Env.SPACE_STORAGE_SITE_URL }}
    main: ./cmd/space-daemon/main.go
    binary: space
    goos:
      - darwin
    # hooks:
    #   post: gon -log-level debug ci/gon.hcl

  - id: space-win
    # env:
    #   - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.mongousr={{ .Env.MONGO_USR }}
      - -X main.mongopw={{ .Env.MONGO_PW }}
      - -X main.mongohost={{ .Env.MONGO_HOST }}
      - -X main.mongorepset={{ .Env.MONGO_REPLICA_SET }}
      - -X main.spaceapi={{ .Env.SERVICES_API_URL }}
      - -X main.vaultapi={{ .Env.VAULT_API_URL }}
      - -X main.vaultsaltsecret={{ .Env.VAULT_SALT_SECRET }}
      - -X main.spacehubauth={{ .Env.SERVICES_HUB_AUTH_URL }}
      - -X main.textilehub={{ .Env.TXL_HUB_TARGET }}
      - -X main.textilehubma={{ .Env.TXL_HUB_MA }}
      - -X main.textilethreads={{ .Env.TXL_THREADS_TARGET }}
      - -X main.textilehubgatewayurl={{ .Env.TXL_HUB_GATEWAY_URL }}
      - -X main.textileuserkey={{ .Env.TXL_USER_KEY }}
      - -X main.textileusersecret={{ .Env.TXL_USER_SECRET }}
      - -X main.spacestoragesiteurl={{ .Env.SPACE_STORAGE_SITE_URL }}
    main: ./cmd/space-daemon/main.go
    binary: space
    goos:
      - windows
    # ignore:
    #   - goos: windows
    #     goarch: 386
archives:
- name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
  format: binary
  files:
    - LICENSE*
    - README*
    - CHANGELOG*
    - dist/space-macos-i386.dmg
    - dist/space-macos-x86_64.dmg
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
