version: '3.7'

services:
  ipfs:
    image: ipfs/go-ipfs:v0.6.0
    ports:
      - 5001:5001

  lotus:
    image: textile/lotus-devnet:ntwk-calibration-8.13.1.f0942
    ports:
      - 7777:7777
    environment:
      - TEXLOTUSDEVNET_SPEED=500
      - TEXLOTUSDEVNET_BIGSECTORS=false
      - TEXLOTUSDEVNET_IPFSADDR=/dns4/ipfs/tcp/5001
