// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Config is an autogenerated mock type for the Config type
type Config struct {
	mock.Mock
}

// GetBool provides a mock function with given fields: key, defaultValue
func (_m *Config) GetBool(key string, defaultValue interface{}) bool {
	ret := _m.Called(key, defaultValue)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, interface{}) bool); ok {
		r0 = rf(key, defaultValue)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetInt provides a mock function with given fields: key, defaultValue
func (_m *Config) GetInt(key string, defaultValue interface{}) int {
	ret := _m.Called(key, defaultValue)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, interface{}) int); ok {
		r0 = rf(key, defaultValue)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetString provides a mock function with given fields: key, defaultValue
func (_m *Config) GetString(key string, defaultValue interface{}) string {
	ret := _m.Called(key, defaultValue)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, interface{}) string); ok {
		r0 = rf(key, defaultValue)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
