// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	domain "github.com/FleekHQ/space-poc/core/space/domain"
	mock "github.com/stretchr/testify/mock"
)

// Syncer is an autogenerated mock type for the Syncer type
type Syncer struct {
	mock.Mock
}

// AddFileWatch provides a mock function with given fields: addFileInfo
func (_m *Syncer) AddFileWatch(addFileInfo domain.AddWatchFile) error {
	ret := _m.Called(addFileInfo)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.AddWatchFile) error); ok {
		r0 = rf(addFileInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOpenFilePath provides a mock function with given fields: bucketSlug, bucketPath
func (_m *Syncer) GetOpenFilePath(bucketSlug string, bucketPath string) (string, bool) {
	ret := _m.Called(bucketSlug, bucketPath)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(bucketSlug, bucketPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string, string) bool); ok {
		r1 = rf(bucketSlug, bucketPath)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}
