// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	events "github.com/FleekHQ/space-poc/core/events"
	mock "github.com/stretchr/testify/mock"
)

// TextileNotifier is an autogenerated mock type for the TextileNotifier type
type TextileNotifier struct {
	mock.Mock
}

// SendTextileEvent provides a mock function with given fields: event
func (_m *TextileNotifier) SendTextileEvent(event events.TextileEvent) {
	_m.Called(event)
}
