// Code generated by mockery v2.0.0. DO NOT EDIT.

package mocks

import (
	io "io"

	bucket "github.com/FleekHQ/space-daemon/core/textile/bucket"

	mock "github.com/stretchr/testify/mock"

	path "github.com/ipfs/interface-go-ipfs-core/path"
)

// Bucket is an autogenerated mock type for the Bucket type
type Bucket struct {
	mock.Mock
}

// CreateDirectory provides a mock function with given fields: _a0
func (_m *Bucket) CreateDirectory(_a0 string) (path.Resolved, path.Path, error) {
	ret := _m.Called(_a0)

	var r0 path.Resolved
	if rf, ok := ret.Get(0).(func(string) path.Resolved); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(path.Resolved)
		}
	}

	var r1 path.Path
	if rf, ok := ret.Get(1).(func(string) path.Path); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(path.Path)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DeleteDirOrFile provides a mock function with given fields: _a0
func (_m *Bucket) DeleteDirOrFile(_a0 string) (path.Resolved, error) {
	ret := _m.Called(_a0)

	var r0 path.Resolved
	if rf, ok := ret.Get(0).(func(string) path.Resolved); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(path.Resolved)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DirExists provides a mock function with given fields: _a0
func (_m *Bucket) DirExists(_a0 string) (bool, error) {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileExists provides a mock function with given fields: _a0
func (_m *Bucket) FileExists(_a0 string) (bool, error) {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetData provides a mock function with given fields:
func (_m *Bucket) GetData() bucket.BucketData {
	ret := _m.Called()

	var r0 bucket.BucketData
	if rf, ok := ret.Get(0).(func() bucket.BucketData); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bucket.BucketData)
	}

	return r0
}

// GetFile provides a mock function with given fields: _a0, w
func (_m *Bucket) GetFile(_a0 string, w io.Writer) error {
	ret := _m.Called(_a0, w)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, io.Writer) error); ok {
		r0 = rf(_a0, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Key provides a mock function with given fields:
func (_m *Bucket) Key() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ListDirectory provides a mock function with given fields: _a0
func (_m *Bucket) ListDirectory(_a0 string) (*bucket.DirEntries, error) {
	ret := _m.Called(_a0)

	var r0 *bucket.DirEntries
	if rf, ok := ret.Get(0).(func(string) *bucket.DirEntries); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bucket.DirEntries)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Slug provides a mock function with given fields:
func (_m *Bucket) Slug() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// UploadFile provides a mock function with given fields: _a0, reader
func (_m *Bucket) UploadFile(_a0 string, reader io.Reader) (path.Resolved, path.Path, error) {
	ret := _m.Called(_a0, reader)

	var r0 path.Resolved
	if rf, ok := ret.Get(0).(func(string, io.Reader) path.Resolved); ok {
		r0 = rf(_a0, reader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(path.Resolved)
		}
	}

	var r1 path.Path
	if rf, ok := ret.Get(1).(func(string, io.Reader) path.Path); ok {
		r1 = rf(_a0, reader)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(path.Path)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, io.Reader) error); ok {
		r2 = rf(_a0, reader)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
