// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/FleekHQ/space-daemon/core/space/domain"
	mock "github.com/stretchr/testify/mock"

	vault "github.com/FleekHQ/space-daemon/core/vault"
)

// Vault is an autogenerated mock type for the Vault type
type Vault struct {
	mock.Mock
}

// Retrieve provides a mock function with given fields: uuid, passphrase, backupType
func (_m *Vault) Retrieve(uuid string, passphrase string, backupType domain.KeyBackupType) ([]vault.VaultItem, error) {
	ret := _m.Called(uuid, passphrase, backupType)

	var r0 []vault.VaultItem
	if rf, ok := ret.Get(0).(func(string, string, domain.KeyBackupType) []vault.VaultItem); ok {
		r0 = rf(uuid, passphrase, backupType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]vault.VaultItem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, domain.KeyBackupType) error); ok {
		r1 = rf(uuid, passphrase, backupType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: uuid, passphrase, backupType, apiToken, items
func (_m *Vault) Store(uuid string, passphrase string, backupType domain.KeyBackupType, apiToken string, items []vault.VaultItem) (*vault.StoredVault, error) {
	ret := _m.Called(uuid, passphrase, backupType, apiToken, items)

	var r0 *vault.StoredVault
	if rf, ok := ret.Get(0).(func(string, string, domain.KeyBackupType, string, []vault.VaultItem) *vault.StoredVault); ok {
		r0 = rf(uuid, passphrase, backupType, apiToken, items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vault.StoredVault)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, domain.KeyBackupType, string, []vault.VaultItem) error); ok {
		r1 = rf(uuid, passphrase, backupType, apiToken, items)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
