// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SpaceEnv is an autogenerated mock type for the SpaceEnv type
type SpaceEnv struct {
	mock.Mock
}

// CurrentFolder provides a mock function with given fields:
func (_m *SpaceEnv) CurrentFolder() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogLevel provides a mock function with given fields:
func (_m *SpaceEnv) LogLevel() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// WorkingFolder provides a mock function with given fields:
func (_m *SpaceEnv) WorkingFolder() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
